Repository jbpayne/TechTalentInfiniti, pull requests merged in 2019-06, with the labels that each got.

#42 Vehicle object
  src/com/tti/MenuSystem.java
  src/com/tti/Test.java
  src/com/tti/Vehicle.java
Labels: size: 5

#56 moved Menu.loadMainMenu inside infinite loop
  src/com/tti/Main.java
Labels: size: 0

#58 added removeVehicle method to VehicleInventory class
  src/com/tti/VehicleInventory.java
Labels: size: 1

#57 change VehicleInventory hashmap keys to use stock number
  src/com/tti/Menu.java
  src/com/tti/VehicleInventory.java
Labels: size: 2

#78 When Lease is selected on Front Desk Menu, only display isLeasable vehicles
  src/com/tti/FrontDeskMenu.java
  src/com/tti/VehicleInventory.java
  test/com/tti/VehicleInventoryTest.java
Labels: size: 2

#75 Make changes to LightTruck class and related classes
  src/com/tti/LightTruck.java
  src/com/tti/SalesMenu.java
  src/com/tti/VehicleInventory.java
Labels: size: 2

#81 Add ILightTruck Interface and Restore Code Lost to Merge Conflict
  src/com/tti/ILightTruck.java
  src/com/tti/LightTruck.java
  src/com/tti/SalesMenu.java
  src/com/tti/VehicleInventory.java
Labels: size: 2

#86 Define Vehicle.getMileagePenalty Method
  src/com/tti/Vehicle.java
Labels: size: 0
